name: document-comparison
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - flask==2.3.3
    - flask-cors==4.0.0
    - nltk==3.8.1
    - numpy==1.24.3
    - scipy==1.10.1
    - scikit-learn==1.2.2
    - python-dotenv==1.0.0
    - textdistance==4.5.0